# Generated by Django 4.2.5 on 2023-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('studio', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
