# Generated by Django 4.2.5 on 2023-10-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesJeux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('date_creation', models.DateField()),
                ('jeux_cree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jeux_cree', to='lesJeux.jeux')),
            ],
        ),
    ]
