# Generated by Django 4.2.5 on 2023-10-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesJeux', '0002_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='description',
            new_name='descriptionS',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='nom',
            new_name='nomS',
        ),
    ]
