# Generated by Django 4.2.5 on 2023-10-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesJeux', '0003_rename_description_studio_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='descriptionS',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='nomS',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='jeux_cree',
        ),
        migrations.AlterField(
            model_name='jeux',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='lesJeux.studio'),
        ),
    ]
