# Generated by Django 4.2.5 on 2023-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesJeux', '0004_rename_descriptions_studio_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='jeux',
            name='tags',
        ),
        migrations.AddField(
            model_name='jeux',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='lesJeux.tag'),
        ),
    ]
