# Generated by Django 4.2.5 on 2023-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesJeux', '0005_tag_remove_jeux_tags_jeux_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
